=== Pull Requests

In essence pull requests are very simple, but they can get confusing to newbies
because of all the other concepts that are related and can complicate discussion
about them.

Fortunately you've covered them, so you are ready!

- remotes
- branches
- repository relationships
- reconciling remote branches

A pull request is a request from a user for another user 

This request can come in any form at all that makes sense. You can send an email
with the diffs to the maintainer, fork and branch, then send a reference to the
branch, branch on the maintainer's repo and mail them the branch name, 
put a request in plain English on a post-it - whatever works!

We're going to focus here on the standard GitHub pull request model.

==== GitHub pull requests

For this section 

The standard GitHub model is to:

- Fork the repository
- Make a branch on the forked repository
- Make changes on this branch
- Make a pull request to the original repository to merge this branch's changes

Your task now is to do this on the GitHub repository!

There is a file called 'records/trained_users.txt' in the repository of this
course. You're going to add your name to it and raise that change as a 
Pull Request.

Remember that this is just one model of pull request! We will talk about
other models later.

If you haven't created a GitHub account, please do so now. It's free. Go to
https://github.com and sign up.

===== Fork the Repository

Next you need to fork the repository. To do this, go to the
'learn-git-the-hard-way' repository on GitHub:

https://github.com/ianmiell/learn-git-the-hard-way 

and click on the 'Fork' button near the top.

You will now have created a fork of the repository in your own account. Replace
YOURUSERNAME with your username in the below URL and you should see the same 
repository homepage:

https://github.com/YOURUSERNAME/learn-git-the-hard-way 

===== Branch on the Forked Repository

To make a branch on your forked repository, type in these commands:

----
$ git clone https://github.com/YOURUSERNAME/learn-git-the-hard-way
$ cd learn-git-the-hard-way
$ git checkout -b myfirstbranch
$ git status
----

You just cloned your forked version of the repository, and created a branch
called 'myfirstbranch'. As ever, running git status gives you a quick view
of which branch you're on.


==== Make Change on the Branch

Now type in these commands to make a change and push it to GitHub:

----
$ echo 'my change to the README' >> README.md
$ git commit -am 'my change to the README'
$ git push -u origin myfirstbranch
----

The first command adds a line to the README.md file. The second commits the
change you made to this new branch.






TODO: diagram of the repositories involved:
- maintainer's repo (GitHub)
- forked repo (GitHub)
- clone from fork (local)
- branch (local)

Make sure these relationships are clear in your mind!



TODO: change
//vi

TODO: commit
//git commit
//git push origin yourbranchname:yourbranchname
TODO: what we have done
TODO: diagram of the repositories involved:
- maintainer's repo (GitHub)
- forked repo (GitHub)
- clone from fork (local)
- branch (local)
- commit (local)
- branch on forked repo (GitHub)


==== Make Pull Request

Now you have a branch on the forked repository on GitHub, you want to get that
branch's changes into the maintainer's repository. This is where you raise the
pull request.

Go to GitHub in a browser and view your repository:

https://github.com/YOURUSERNAME/learn-git-the-hard-way 

TODO: Go to the branch

TODO: Click make pull request (?). Fill out the form

TODO: What to do next


==== 

=== Pull Requests in Practice - Rebasing

Maintainers will often ask that you rebase your branch before making a pull 
request.

TODO: refer to rebase section, describe

