graph LR
    MR(Maintainer's Repo)-- forked into >FR(Forked Repo)
    FR-- cloned from fork >LR(Local Repo)
    LR-- branched to myfirstbranch >LB(Local branch)
    LR-- branch on forked repo >LB(Local branch)
    LB-- commit change >LC(Local commit)
	LC-- pushed to >LR
